//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfFIARService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameId { get; set; }
        public bool GameOver { get; set; }
        public System.DateTime GameStart { get; set; }
        public int Player1Points { get; set; }
        public int Player2Points { get; set; }
        public Nullable<int> Player_PlayerId { get; set; }
        public Nullable<int> PlayedAgainst_PlayerId { get; set; }
        public Nullable<int> Winner_PlayerId { get; set; }
    
        public virtual Player Player2 { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual Player Winner { get; set; }
    }
}
